
#myapp:
#  username: lucy
#  email: lucy@456.com
#  age: 60
#  gender: false
---
myapp:
#  username: 'lu\ncy'
  username: |
    aaaa
    bbbb
    cccc
    dddd
  email: "lucy\n@456.com"
  age: 60
  gender: false

---
myapp2:
  username: zhangsan
  email: zhangsan@123.com
  age: 20
  gender: false